#!/usr/bin/env node

/**
 * Setup Script: Configure Environment Variables
 * 
 * This script helps you set up the .env file with Supabase credentials.
 * Run: node scripts/setup-env.js
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');
const envPath = path.join(projectRoot, '.env');

const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  bold: '\x1b[1m',
};

const log = {
  error: (msg) => console.log(`${colors.red}❌ ${msg}${colors.reset}`),
  success: (msg) => console.log(`${colors.green}✅ ${msg}${colors.reset}`),
  info: (msg) => console.log(`${colors.cyan}ℹ️  ${msg}${colors.reset}`),
  warn: (msg) => console.log(`${colors.yellow}⚠️  ${msg}${colors.reset}`),
  header: (msg) => console.log(`\n${colors.bold}${colors.cyan}${msg}${colors.reset}\n`),
};

function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function getUserInput(prompt) {
  return new Promise((resolve) => {
    const rl = createInterface();
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function getSecretInput(prompt) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: true,
    });

    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

function validateUrl(url) {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
}

function checkEnvExists() {
  return fs.existsSync(envPath);
}

function readExistingEnv() {
  if (!checkEnvExists()) return {};

  const content = fs.readFileSync(envPath, 'utf-8');
  const env = {};

  content.split('\n').forEach((line) => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      env[match[1].trim()] = match[2].trim();
    }
  });

  return env;
}

function createEnvContent(url, key) {
  return `# Supabase Configuration
# Generated by setup-env.js on ${new Date().toISOString()}

SUPABASE_URL=${url}
SUPABASE_SERVICE_ROLE_KEY=${key}

# Environment
NODE_ENV=development
`;
}

function saveEnvFile(content) {
  fs.writeFileSync(envPath, content, 'utf-8');
}

function checkGitignore() {
  const gitignorePath = path.join(projectRoot, '.gitignore');

  if (!fs.existsSync(gitignorePath)) {
    log.warn('.gitignore file not found');
    return false;
  }

  const content = fs.readFileSync(gitignorePath, 'utf-8');
  return content.includes('.env');
}

function addToGitignore() {
  const gitignorePath = path.join(projectRoot, '.gitignore');

  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, '.env\n', 'utf-8');
    log.success('Created .gitignore and added .env');
    return;
  }

  const content = fs.readFileSync(gitignorePath, 'utf-8');

  if (!content.includes('.env')) {
    fs.appendFileSync(gitignorePath, '\n.env\n', 'utf-8');
    log.success('Added .env to .gitignore');
  } else {
    log.info('.env already in .gitignore');
  }
}

async function main() {
  console.clear();
  log.header('🔐 Environment Setup - Supabase Configuration');

  // Check if .env already exists
  const envExists = checkEnvExists();
  if (envExists) {
    log.info('.env file already exists');
    const overwrite = await getUserInput('Do you want to update it? (yes/no): ');

    if (overwrite.toLowerCase() !== 'yes' && overwrite.toLowerCase() !== 'y') {
      log.info('Setup cancelled');
      process.exit(0);
    }

    log.info('Loading existing values...');
  }

  console.log('');
  log.info('Get your Supabase credentials from:');
  console.log('  1. Go to https://app.supabase.com');
  console.log('  2. Select your project');
  console.log('  3. Settings → API');
  console.log('  4. Copy the URLs and keys below\n');

  // Get Supabase URL
  let supabaseUrl = '';
  while (!supabaseUrl) {
    supabaseUrl = await getUserInput('Enter your SUPABASE_URL (e.g., https://xyz.supabase.co): ');

    if (!validateUrl(supabaseUrl)) {
      log.error('Invalid URL format. Please try again.');
      supabaseUrl = '';
    }
  }

  // Get Service Role Key
  let serviceRoleKey = '';
  while (!serviceRoleKey) {
    serviceRoleKey = await getSecretInput('Enter your SUPABASE_SERVICE_ROLE_KEY (input hidden): ');

    if (serviceRoleKey.length < 20) {
      log.error('Service role key seems too short. Please try again.');
      serviceRoleKey = '';
    }
  }

  // Show summary
  console.log('');
  log.info('Configuration Summary:');
  console.log(`  SUPABASE_URL: ${supabaseUrl}`);
  console.log(`  SERVICE_ROLE_KEY: ${serviceRoleKey.substring(0, 20)}...`);
  console.log('');

  // Confirm
  const confirm = await getUserInput('Is this correct? (yes/no): ');

  if (confirm.toLowerCase() !== 'yes' && confirm.toLowerCase() !== 'y') {
    log.warn('Setup cancelled');
    process.exit(0);
  }

  // Save .env file
  try {
    const envContent = createEnvContent(supabaseUrl, serviceRoleKey);
    saveEnvFile(envContent);
    log.success(`.env file saved to ${envPath}`);
  } catch (error) {
    log.error(`Failed to save .env file: ${error.message}`);
    process.exit(1);
  }

  // Update .gitignore
  try {
    addToGitignore();
  } catch (error) {
    log.warn(`Could not update .gitignore: ${error.message}`);
  }

  // Check .gitignore
  if (checkGitignore()) {
    log.success('.env is protected in .gitignore');
  } else {
    log.warn('Please make sure .env is in your .gitignore file');
  }

  // Final instructions
  console.log('');
  log.header('✅ Setup Complete!');

  console.log('You can now use the reset password script:');
  console.log(`  ${colors.cyan}node scripts/reset-password-cli.js${colors.reset}\n`);

  console.log('Or use npm script (if configured):');
  console.log(`  ${colors.cyan}npm run reset-password${colors.reset}\n`);

  log.info('Your credentials are stored in .env (kept secret from git)');
  console.log('');
}

// Run the setup
main().catch((error) => {
  log.error(`Unexpected error: ${error.message}`);
  process.exit(1);
});
